version: '3.8' #https://docs.docker.com/compose/compose-file/compose-versioning/

services:
    postgres:
        image: postgres
        container_name: postgres-blog
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: "SENHA@senha"
        ports:
            - 5432:5432
        networks:
            - blog-network
            
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin-blog
        environment:
            PGADMIN_DEFAULT_EMAIL: "cleytonferrari@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "SENHA@senha"
        ports:
            - '8080:80'
        depends_on: 
            - postgres
        networks:
            - blog-network
    
networks:
    blog-network:
        driver: bridge
