version: '3.8' #https://docs.docker.com/compose/compose-file/compose-versioning/

services:
    postgres:
        image: postgres
        container_name: postgres-blog
        restart: unless-stopped
        environment:
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "SENHA@senha"
            POSTGRES_DB: "blogDb"
        ports:
            - 5432:5432
        restart: always
        volumes:
            - database-data:/var/lib/postgresql/data/
        networks:
            - blog-network
            
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin-blog
        environment:
            PGADMIN_DEFAULT_EMAIL: "cleytonferrari@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "SENHA@senha"
        ports:
            - '8080:80'
        restart: always
        volumes:
            - pgadmin:/root/.pgadmin
        depends_on: 
            - postgres
        networks:
            - blog-network
    
networks:
    blog-network:
        driver: bridge

volumes:
    database-data:
    pgadmin: